definitions:
  main.List:
    properties:
      address:
        type: string
      birthday:
        type: string
      full_name:
        type: string
      id:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Swagger API for Golang Project.
  title: Swagger API
  version: "1.0"
paths:
  /lists:
    get:
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.List'
            type: array
swagger: "2.0"
