definitions:
  main.List:
    properties:
      address:
        type: string
      birthday:
        type: string
      full_name:
        type: string
      id:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Swagger API for Golang Project.
  title: Swagger API
  version: "1.0"
paths:
  /lists:
    get:
      consumes:
      - application/json
      description: Get all
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.List'
            type: array
      summary: Show all
      tags:
      - lists
  /lists/{id}:
    delete:
      consumes:
      - application/json
      description: Delete list
      parameters:
      - description: List ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "404":
          description: Not Found
          schema:
            type: string
      summary: Delete by Id
      tags:
      - lists
swagger: "2.0"
